### ISSUE TITLE
Action may not be able to determine job_id/html_url if run has more than 30 jobs

### ISSUE THREAD

**Issue by IngoStrauch2020** [Tiryoh/gha-jobid-action#1]
### Summary

The jobs API endpoint by default only returns 30 jobs, i.e. currently this action will not be able to determine all job_id/html_url if there are more than 30 jobs in a run.

### Details

The API (see https://docs.github.com/en/rest/reference/actions#list-jobs-for-a-workflow-run) has a URL parameter `per_page` so that one can specify how many entries should be returned. There is a hard limit of 100.

### Suggestions

* quick fix/hack: provide an action input parameter to be able to increase the number of returned jobs in one request
** this will at least help people with runs that contain 31 to 100 jobs
* add some kind of pagination if a run has more jobs than are returned by the API
** use `page` URL parameter of the API depending on the first API response
```
{
  "total_count": 46,
  "jobs": [ ... ]
}
```
So in this example, if `per_page` equals the default value of 30 and the desired job name is not found in this response, perform a second request with `?page=2` and check the second response.

**Comment by Tiryoh** [comment]
Sorry for the late responding. Thanks for your report. I'll look into it.

**Comment by Tiryoh** [comment]
First of all, thanks for pointing this out @IngoStrauch2020.

I have also come to the conclusion that it seems like quick fix of this problem is using `per_page` param of [`List jobs for a workflow run attempt`](https://docs.github.com/en/rest/reference/actions#list-jobs-for-a-workflow-run-attempt) to get the job lists, as you point out.

Also, after digging further, I found there are two ways to get the current job_id.

1. Getting the current job_id directly

I haven't tested yet, but it seems like there are some ways to get the current job name using JavaScript actions.

https://github.com/actions/toolkit/issues/550
https://github.com/actions/starter-workflows/issues/292

2. Using Octokit's pagination method to get all job name list

https://octokit.github.io/rest.js/v18#pagination
ref: https://maku.blog/p/7r6gr3d/ (written in Japanese)

I would like to support up to 100 jobs first, and then rewrite this action using Octokit.

**Comment by Tiryoh** [comment]
I have added the followings.

* an option parameter, `per_page` in PR #8 
* some tests including test for workflow that has more than 31 jobs in PR #6

I'm not having any trouble with Docker at this moment, so not in a hurry to upgrade using Octokit, but I'll make sure I do.

**Comment by Tiryoh** [comment]
I'm closing this issue because it is now possible to get the job_id even if there are more than 30 jobs.
Further improvements will be taken over in #10.
